#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../headers/pagerank.h"

/**
 * @brief Apply PageRank algorithm
 * on a transition matrix
 * 
 * @param matrix the transition matrix 
 * @param d the damping factor, usually 0.85
 * @param epsilon 
 * @param max_iterations maximum iterations
 * @return the eigen vector generated by PageRank algorithm
 */
Vector apply_pagerank(Matrix matrix, double d, double epsilon, int max_iterations, int *iterations_count) {
  int nodes_count = matrix.colums_number;
  // Initial vector
  Vector v, previous_v;
  double err;

  v.length = nodes_count;
  allocate_vector(&v);
  int i,j;
  double norm;
  

  for (i = 0; i < nodes_count; i++)
    v.array[i] = 1.0 / (double) nodes_count;

  for (i = 0; i < max_iterations; i++) {
    previous_v = v;
    v = matrix_dot_vector(matrix, v);
    /* norm = compute_norm(v);
    double_divide_vector(&v, norm);  */ 

    for (j = 0; j < nodes_count; j++)
      v.array[j] = v.array[j] * d + (1.0 - d) / (double) nodes_count;

    err = 0;

    for (j = 0; j < nodes_count; j++)
      err += fabs(v.array[j] - previous_v.array[j]);

    *iterations_count = i;

    if (err < epsilon) {
      return v;
    }
  }

  return v;
}

int write_perf(double damping_factor, int iterations) {
  char *file_path = "output/performance.txt";
  FILE *file_pointer = fopen(file_path, "a");
  int written_chars_count = 0;

  if (file_pointer == NULL) {
    printf("Impossible d'ouvrir le fichier %s\n", file_path);
    exit(EXIT_FAILURE);
  }

  written_chars_count = fprintf(file_pointer, "%lf; %d\n", damping_factor, iterations);
  fclose(file_pointer);

  return written_chars_count;
}